import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React from 'react'
import Link from 'next/link'

export async function getStaticProps() {
  const data = await fetch("https://restcountries.com/v2/lang/fr")
  .then(resp=>resp.json());

  return{
    props:
    {
      data, 
    }
  }
}


export default function Home({data}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Countries App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ul>
          {
            data?.map(item=>(
              <li key={item.name}>
                <Link href={`/countries/${item.name}`}>
                  <a>{item.name}</a>
                </Link>
              </li>
            ))
          }
        </ul>
      </main>
    </div>
  )
}
